---
name: Checks

on: [push]

jobs:
  test-lint: #id
    name: Test and Lint
    runs-on: ubuntu-20.04 # runner available in github actions
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1 # use premade action from github actions. Action to login to Docker.
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2 # action to access the code (made available for next steps)
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test" # run unit test
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"